name: rich_editor_demo
description: Demo app for the rich editor.

dependencies:
  flutter:
    sdk: flutter

  rich_editor:
    path: ../rich_editor

  cupertino_icons: any


flutter:

  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0 <3.0.0"